export enum FEATURES {
    TEMPLATES = "TEMPLATES",
    TEMPLATE_ADD = "TEMPLATE_ADD",
    TEMPLATE_UPDATE = "TEMPLATE_UPDATE",
    TEMPLATE_DELETE = "TEMPLATE_DELETE",
    TEMPLATE_DETAIL = "TEMPLATE_DETAIL",
    SLIDES_LIST = "SLIDES_LIST",
    SLIDE_ADD = "SLIDE_ADD",
    SLIDE_UPDATE = "SLIDE_UPDATE",
    SLIDE_DELETE = "SLIDE_DELETE",
    SLIDE_DETAIL = "SLIDE_DETAIL",
}